#!/usr/bin/env bash

echo 'Submitting jobscript_ExpConstruction_PropMin11.job'
sbatch jobscript_ExpConstruction_PropMin11.job
echo 'Submitting jobscript_ExpConstruction_PropMin12.job'
sbatch jobscript_ExpConstruction_PropMin12.job
echo 'Submitting jobscript_ExpConstruction_PropMin13.job'
sbatch jobscript_ExpConstruction_PropMin13.job
echo 'Submitting jobscript_ExpConstruction_PropMin14.job'
sbatch jobscript_ExpConstruction_PropMin14.job
echo 'Submitting jobscript_ExpConstruction_PropMin15.job'
sbatch jobscript_ExpConstruction_PropMin15.job
echo 'Submitting jobscript_ExpConstruction_PropMin16.job'
sbatch jobscript_ExpConstruction_PropMin16.job
echo 'Submitting jobscript_ExpConstruction_PropMin17.job'
sbatch jobscript_ExpConstruction_PropMin17.job
echo 'Submitting jobscript_ExpConstruction_PropMin18.job'
sbatch jobscript_ExpConstruction_PropMin18.job
echo 'Submitting jobscript_ExpConstruction_PropMin19.job'
sbatch jobscript_ExpConstruction_PropMin19.job
echo 'Submitting jobscript_ExpConstruction_PropMin20.job'
sbatch jobscript_ExpConstruction_PropMin20.job
