#!/usr/bin/env bash

echo 'Submitting jobscript_ExpAgricultural_Both11.job'
sbatch jobscript_ExpAgricultural_Both11.job
echo 'Submitting jobscript_ExpAgricultural_Both12.job'
sbatch jobscript_ExpAgricultural_Both12.job
echo 'Submitting jobscript_ExpAgricultural_Both13.job'
sbatch jobscript_ExpAgricultural_Both13.job
echo 'Submitting jobscript_ExpAgricultural_Both14.job'
sbatch jobscript_ExpAgricultural_Both14.job
echo 'Submitting jobscript_ExpAgricultural_Both15.job'
sbatch jobscript_ExpAgricultural_Both15.job
echo 'Submitting jobscript_ExpAgricultural_Both16.job'
sbatch jobscript_ExpAgricultural_Both16.job
echo 'Submitting jobscript_ExpAgricultural_Both17.job'
sbatch jobscript_ExpAgricultural_Both17.job
echo 'Submitting jobscript_ExpAgricultural_Both18.job'
sbatch jobscript_ExpAgricultural_Both18.job
echo 'Submitting jobscript_ExpAgricultural_Both19.job'
sbatch jobscript_ExpAgricultural_Both19.job
echo 'Submitting jobscript_ExpAgricultural_Both20.job'
sbatch jobscript_ExpAgricultural_Both20.job
