#!/usr/bin/env bash

echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment1.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment1.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment2.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment2.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment3.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment3.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment4.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment4.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment5.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment5.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment6.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment6.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment7.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment7.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment8.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment8.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment9.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment9.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment10.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment10.job
