#!/usr/bin/env bash


echo 'Submitting jobscript_ExpAgricultural_Model1.job'
sbatch jobscript_ExpAgricultural_Model1.job
echo 'Submitting jobscript_ExpAgricultural_Model2.job'
sbatch jobscript_ExpAgricultural_Model2.job
echo 'Submitting jobscript_ExpAgricultural_Model3.job'
sbatch jobscript_ExpAgricultural_Model3.job
echo 'Submitting jobscript_ExpAgricultural_Model4.job'
sbatch jobscript_ExpAgricultural_Model4.job
echo 'Submitting jobscript_ExpAgricultural_Model5.job'
sbatch jobscript_ExpAgricultural_Model5.job
echo 'Submitting jobscript_ExpAgricultural_Model6.job'
sbatch jobscript_ExpAgricultural_Model6.job
echo 'Submitting jobscript_ExpAgricultural_Model7.job'
sbatch jobscript_ExpAgricultural_Model7.job
echo 'Submitting jobscript_ExpAgricultural_Model8.job'
sbatch jobscript_ExpAgricultural_Model8.job
echo 'Submitting jobscript_ExpAgricultural_Model9.job'
sbatch jobscript_ExpAgricultural_Model9.job
echo 'Submitting jobscript_ExpAgricultural_Model10.job'
sbatch jobscript_ExpAgricultural_Model10.job
echo 'Submitting jobscript_ExpAgricultural_None11.job'
sbatch jobscript_ExpAgricultural_None11.job
echo 'Submitting jobscript_ExpAgricultural_None12.job'
sbatch jobscript_ExpAgricultural_None12.job
echo 'Submitting jobscript_ExpAgricultural_None13.job'
sbatch jobscript_ExpAgricultural_None13.job
echo 'Submitting jobscript_ExpAgricultural_None14.job'
sbatch jobscript_ExpAgricultural_None14.job
echo 'Submitting jobscript_ExpAgricultural_None15.job'
sbatch jobscript_ExpAgricultural_None15.job
echo 'Submitting jobscript_ExpAgricultural_None16.job'
sbatch jobscript_ExpAgricultural_None16.job
echo 'Submitting jobscript_ExpAgricultural_None17.job'
sbatch jobscript_ExpAgricultural_None17.job
echo 'Submitting jobscript_ExpAgricultural_None18.job'
sbatch jobscript_ExpAgricultural_None18.job
echo 'Submitting jobscript_ExpAgricultural_None19.job'
sbatch jobscript_ExpAgricultural_None19.job
echo 'Submitting jobscript_ExpAgricultural_None20.job'
sbatch jobscript_ExpAgricultural_None20.job
