#!/usr/bin/env bash

echo 'Submitting jobscript_ExpAgri_ChangeInjectedBoth_experiment1.job'
sbatch jobscript_ExpAgri_ChangeInjectedBoth_experiment1.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedBoth_experiment2.job'
sbatch jobscript_ExpAgri_ChangeInjectedBoth_experiment2.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedBoth_experiment3.job'
sbatch jobscript_ExpAgri_ChangeInjectedBoth_experiment3.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedBoth_experiment4.job'
sbatch jobscript_ExpAgri_ChangeInjectedBoth_experiment4.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedBoth_experiment5.job'
sbatch jobscript_ExpAgri_ChangeInjectedBoth_experiment5.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedBoth_experiment6.job'
sbatch jobscript_ExpAgri_ChangeInjectedBoth_experiment6.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedBoth_experiment7.job'
sbatch jobscript_ExpAgri_ChangeInjectedBoth_experiment7.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedBoth_experiment8.job'
sbatch jobscript_ExpAgri_ChangeInjectedBoth_experiment8.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedBoth_experiment9.job'
sbatch jobscript_ExpAgri_ChangeInjectedBoth_experiment9.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedBoth_experiment10.job'
sbatch jobscript_ExpAgri_ChangeInjectedBoth_experiment10.job
