#!/usr/bin/env bash

echo 'Submitting jobscript_ExpConstruction_Both11.job'
sbatch jobscript_ExpConstruction_Both11.job
echo 'Submitting jobscript_ExpConstruction_Both12.job'
sbatch jobscript_ExpConstruction_Both12.job
echo 'Submitting jobscript_ExpConstruction_Both13.job'
sbatch jobscript_ExpConstruction_Both13.job
echo 'Submitting jobscript_ExpConstruction_Both14.job'
sbatch jobscript_ExpConstruction_Both14.job
echo 'Submitting jobscript_ExpConstruction_Both15.job'
sbatch jobscript_ExpConstruction_Both15.job
echo 'Submitting jobscript_ExpConstruction_Both16.job'
sbatch jobscript_ExpConstruction_Both16.job
echo 'Submitting jobscript_ExpConstruction_Both17.job'
sbatch jobscript_ExpConstruction_Both17.job
echo 'Submitting jobscript_ExpConstruction_Both18.job'
sbatch jobscript_ExpConstruction_Both18.job
echo 'Submitting jobscript_ExpConstruction_Both19.job'
sbatch jobscript_ExpConstruction_Both19.job
echo 'Submitting jobscript_ExpConstruction_Both20.job'
sbatch jobscript_ExpConstruction_Both20.job
