#!/usr/bin/env bash

echo 'Submitting jobscript_ExpAgricultural_None1.job'
sbatch jobscript_ExpAgricultural_None1.job
echo 'Submitting jobscript_ExpAgricultural_None2.job'
sbatch jobscript_ExpAgricultural_None2.job
echo 'Submitting jobscript_ExpAgricultural_None3.job'
sbatch jobscript_ExpAgricultural_None3.job
echo 'Submitting jobscript_ExpAgricultural_None4.job'
sbatch jobscript_ExpAgricultural_None4.job
echo 'Submitting jobscript_ExpAgricultural_None5.job'
sbatch jobscript_ExpAgricultural_None5.job
echo 'Submitting jobscript_ExpAgricultural_None6.job'
sbatch jobscript_ExpAgricultural_None6.job
echo 'Submitting jobscript_ExpAgricultural_None7.job'
sbatch jobscript_ExpAgricultural_None7.job
echo 'Submitting jobscript_ExpAgricultural_None8.job'
sbatch jobscript_ExpAgricultural_None8.job
echo 'Submitting jobscript_ExpAgricultural_None9.job'
sbatch jobscript_ExpAgricultural_None9.job
echo 'Submitting jobscript_ExpAgricultural_None10.job'
sbatch jobscript_ExpAgricultural_None10.job
echo 'Submitting jobscript_ExpAgricultural_None11.job'
sbatch jobscript_ExpAgricultural_None11.job
echo 'Submitting jobscript_ExpAgricultural_None12.job'
sbatch jobscript_ExpAgricultural_None12.job
echo 'Submitting jobscript_ExpAgricultural_None13.job'
sbatch jobscript_ExpAgricultural_None13.job
echo 'Submitting jobscript_ExpAgricultural_None14.job'
sbatch jobscript_ExpAgricultural_None14.job
echo 'Submitting jobscript_ExpAgricultural_None15.job'
sbatch jobscript_ExpAgricultural_None15.job
echo 'Submitting jobscript_ExpAgricultural_None16.job'
sbatch jobscript_ExpAgricultural_None16.job
echo 'Submitting jobscript_ExpAgricultural_None17.job'
sbatch jobscript_ExpAgricultural_None17.job
echo 'Submitting jobscript_ExpAgricultural_None18.job'
sbatch jobscript_ExpAgricultural_None18.job
echo 'Submitting jobscript_ExpAgricultural_None19.job'
sbatch jobscript_ExpAgricultural_None19.job
echo 'Submitting jobscript_ExpAgricultural_None20.job'
sbatch jobscript_ExpAgricultural_None20.job
