#!/usr/bin/env bash

echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment11.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment11.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment12.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment12.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment13.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment13.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment14.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment14.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment15.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment15.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment16.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment16.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment17.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment17.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment18.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment18.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment19.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment19.job
echo 'Submitting jobscript_ExpAgri_ChangeInjectedModel_experiment20.job'
sbatch jobscript_ExpAgri_ChangeInjectedModel_experiment20.job
