#!/usr/bin/env bash

echo 'Submitting jobscript_ExpAgricultural_Model11.job'
sbatch jobscript_ExpAgricultural_Model11.job
echo 'Submitting jobscript_ExpAgricultural_Model12.job'
sbatch jobscript_ExpAgricultural_Model12.job
echo 'Submitting jobscript_ExpAgricultural_Model13.job'
sbatch jobscript_ExpAgricultural_Model13.job
echo 'Submitting jobscript_ExpAgricultural_Model14.job'
sbatch jobscript_ExpAgricultural_Model14.job
echo 'Submitting jobscript_ExpAgricultural_Model15.job'
sbatch jobscript_ExpAgricultural_Model15.job
echo 'Submitting jobscript_ExpAgricultural_Model16.job'
sbatch jobscript_ExpAgricultural_Model16.job
echo 'Submitting jobscript_ExpAgricultural_Model17.job'
sbatch jobscript_ExpAgricultural_Model17.job
echo 'Submitting jobscript_ExpAgricultural_Model18.job'
sbatch jobscript_ExpAgricultural_Model18.job
echo 'Submitting jobscript_ExpAgricultural_Model19.job'
sbatch jobscript_ExpAgricultural_Model19.job
echo 'Submitting jobscript_ExpAgricultural_Model20.job'
sbatch jobscript_ExpAgricultural_Model20.job
