#!/usr/bin/env bash

echo 'Submitting jobscript_ExpAgricultural_None11.job'
sbatch jobscript_ExpAgricultural_None11.job
echo 'Submitting jobscript_ExpAgricultural_None12.job'
sbatch jobscript_ExpAgricultural_None12.job
echo 'Submitting jobscript_ExpAgricultural_None13.job'
sbatch jobscript_ExpAgricultural_None13.job
echo 'Submitting jobscript_ExpAgricultural_None14.job'
sbatch jobscript_ExpAgricultural_None14.job
echo 'Submitting jobscript_ExpAgricultural_None15.job'
sbatch jobscript_ExpAgricultural_None15.job
echo 'Submitting jobscript_ExpAgricultural_None16.job'
sbatch jobscript_ExpAgricultural_None16.job
echo 'Submitting jobscript_ExpAgricultural_None17.job'
sbatch jobscript_ExpAgricultural_None17.job
echo 'Submitting jobscript_ExpAgricultural_None18.job'
sbatch jobscript_ExpAgricultural_None18.job
echo 'Submitting jobscript_ExpAgricultural_None19.job'
sbatch jobscript_ExpAgricultural_None19.job
echo 'Submitting jobscript_ExpAgricultural_None20.job'
sbatch jobscript_ExpAgricultural_None20.job
