#!/usr/bin/env bash

echo 'Submitting jobscript_ExpAgricultural_PropLarge11.job'
sbatch jobscript_ExpAgricultural_PropLarge11.job
echo 'Submitting jobscript_ExpAgricultural_PropLarge12.job'
sbatch jobscript_ExpAgricultural_PropLarge12.job
echo 'Submitting jobscript_ExpAgricultural_PropLarge13.job'
sbatch jobscript_ExpAgricultural_PropLarge13.job
echo 'Submitting jobscript_ExpAgricultural_PropLarge14.job'
sbatch jobscript_ExpAgricultural_PropLarge14.job
echo 'Submitting jobscript_ExpAgricultural_PropLarge15.job'
sbatch jobscript_ExpAgricultural_PropLarge15.job
echo 'Submitting jobscript_ExpAgricultural_PropLarge16.job'
sbatch jobscript_ExpAgricultural_PropLarge16.job
echo 'Submitting jobscript_ExpAgricultural_PropLarge17.job'
sbatch jobscript_ExpAgricultural_PropLarge17.job
echo 'Submitting jobscript_ExpAgricultural_PropLarge18.job'
sbatch jobscript_ExpAgricultural_PropLarge18.job
echo 'Submitting jobscript_ExpAgricultural_PropLarge19.job'
sbatch jobscript_ExpAgricultural_PropLarge19.job
echo 'Submitting jobscript_ExpAgricultural_PropLarge20.job'
sbatch jobscript_ExpAgricultural_PropLarge20.job
